### ISSUE TITLE
deprecated use of `core.*` functions

### ISSUE THREAD

**Issue by BuckarooBanzay** [zmv7/minetest-mod-luabutton#1]
you might want to change the `core.*` functions to `minetest.*` (just a suggestion, feel free to ignore me :)

**Comment by zeminori** [comment]
Alrighty. Technically `core == minetest` but many people say that `core` violates modding aesthetics, heh. So, I got fixed this in [cb73b46](https://github.com/zmv7/minetest-mod-luabutton/commit/cb73b46012f8340debf6704fb6c4fc0a6bf3c7a3)
