### ISSUE TITLE
`code` metadata field is not marked as private

### ISSUE THREAD

**Issue by appgurueu** [zmv7/minetest-mod-luabutton#2]
Use `meta:mark_as_private("code")` after setting the field to mark it as private. This will:

1. Avoid unnecessarily sending the code to players, saving traffic;
2. Make sure that unauthorized players aren't sent the code

**Comment by zeminori** [comment]
Oh, thanks for an advice, it's actually important. Applied in [cb73b46](https://github.com/zmv7/minetest-mod-luabutton/commit/cb73b46012f8340debf6704fb6c4fc0a6bf3c7a3)
